// =============================================================================
//  axil_coverage.svh  -  functional coverage collector
//  Subscribes to the monitor's analysis port and samples every completed
//  AXI4-Lite transaction.  Unreachable / negative bins are excluded with
//  ignore_bins so 100% means "all reachable behaviour was exercised".
// =============================================================================
class axil_coverage extends uvm_subscriber #(axil_item);
    `uvm_component_utils(axil_coverage)

    axil_item tr;

    covergroup cg;
        option.per_instance = 1;

        // read vs write
        cp_rw: coverpoint tr.is_write {
            bins rd = {0};
            bins wr = {1};
        }

        // which register (addr >> 2). idx 10,11 are unmapped -> not binned.
        cp_reg: coverpoint (tr.addr >> 2) {
            bins key[]  = {[0:3]};     // KEY0..KEY3
            bins pt[]   = {[4:7]};     // PT0..PT3
            bins ctrl   = {8};
            bins status = {9};
            bins ct[]   = {[12:15]};   // CIPHERTEXT0..3
        }

        // write strobe (partial-byte coverage)
        cp_strb: coverpoint tr.strb {
            bins full    = {4'hF};
            bins partial = {[4'h1:4'hE]};
            bins none    = {4'h0};
        }

        // bus response : OKAY for mapped, SLVERR for unmapped/out-of-range.
        // EXOKAY(01)/DECERR(11) are not generated by this slave.
        cp_resp: coverpoint tr.resp {
            bins okay   = {2'b00};
            bins slverr = {2'b10};
            ignore_bins na = {2'b01, 2'b11};
        }

        // direction x register; KEY/PT/CTRL writable, STATUS/CT read-only
        x_rw_reg: cross cp_rw, cp_reg {
            // RO registers are never written -> exclude those cross bins
            ignore_bins wr_ro = binsof(cp_rw.wr) &&
                                (binsof(cp_reg) intersect {9, 12, 13, 14, 15});
        }
    endgroup

    function new(string name, uvm_component parent);
        super.new(name, parent);
        cg = new();
    endfunction

    // called by the analysis port for each transaction
    function void write(axil_item t);
        tr = t;
        cg.sample();
    endfunction

    function void report_phase(uvm_phase phase);
        super.report_phase(phase);
        `uvm_info("COV", $sformatf("functional coverage = %0.2f %%",
                                   cg.get_inst_coverage()), UVM_NONE)
    endfunction
endclass
